global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'hyperliquid-bot'
    environment: 'production'

scrape_configs:
  # Bot metrics
  - job_name: 'hyperliquid-bot'
    static_configs:
      - targets: ['bot:4000']
    metrics_path: '/api/prometheus'
    scrape_interval: 5s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - '/etc/prometheus/alerts.yml'
